# params:
# - dvclive/params.yaml
stages:
  train:
    cmd: python train.py
    deps:
    - train.py
    params:
    - train
    outs:
    - dvclive
params:
- dvclive/params.yaml
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
